package Vista;

/**
 *
 * @author Fernando garces
 */
public class PantallaFichaPago extends javax.swing.JPanel {

    /**
     * Creates new form PantallaFichaPago
     */
    public PantallaFichaPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneralInscripciones = new javax.swing.JPanel();
        PanelTitulo = new javax.swing.JPanel();
        labelTitulo1 = new javax.swing.JLabel();
        panelFichaPago = new javax.swing.JPanel();
        labelTitulo3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelTotalFinalPagar = new javax.swing.JLabel();
        labelTitulo5 = new javax.swing.JLabel();
        btnNuevaInscripcion = new javax.swing.JButton();
        labelFechaEmision = new javax.swing.JLabel();
        labelIdTransaccion = new javax.swing.JLabel();
        labelTitulo4 = new javax.swing.JLabel();

        PanelGeneralInscripciones.setBackground(new java.awt.Color(255, 255, 255));

        PanelTitulo.setBackground(new java.awt.Color(102, 0, 204));

        labelTitulo1.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        labelTitulo1.setText("Ficha de pago - ITSON");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTitulo1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelFichaPago.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout panelFichaPagoLayout = new javax.swing.GroupLayout(panelFichaPago);
        panelFichaPago.setLayout(panelFichaPagoLayout);
        panelFichaPagoLayout.setHorizontalGroup(
            panelFichaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        panelFichaPagoLayout.setVerticalGroup(
            panelFichaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        labelTitulo3.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        labelTitulo3.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo3.setText("Curso");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelTotalFinalPagar.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        labelTotalFinalPagar.setForeground(new java.awt.Color(51, 51, 255));
        labelTotalFinalPagar.setText("$0.00");

        labelTitulo5.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        labelTitulo5.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo5.setText("TOTAL FINAL");

        btnNuevaInscripcion.setBackground(new java.awt.Color(102, 51, 255));
        btnNuevaInscripcion.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        btnNuevaInscripcion.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaInscripcion.setText("Nueva inscripcion");
        btnNuevaInscripcion.addActionListener(this::btnNuevaInscripcionActionPerformed);

        labelFechaEmision.setForeground(new java.awt.Color(51, 51, 51));
        labelFechaEmision.setText("Fecha de emision: ");

        labelIdTransaccion.setForeground(new java.awt.Color(51, 51, 51));
        labelIdTransaccion.setText("ID de transaccion: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(labelTitulo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(labelTotalFinalPagar)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNuevaInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIdTransaccion)
                    .addComponent(labelFechaEmision))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalFinalPagar)
                    .addComponent(labelTitulo5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFechaEmision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIdTransaccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnNuevaInscripcion)
                .addContainerGap())
        );

        labelTitulo4.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        labelTitulo4.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo4.setText("Costo");

        javax.swing.GroupLayout PanelGeneralInscripcionesLayout = new javax.swing.GroupLayout(PanelGeneralInscripciones);
        PanelGeneralInscripciones.setLayout(PanelGeneralInscripcionesLayout);
        PanelGeneralInscripcionesLayout.setHorizontalGroup(
            PanelGeneralInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelGeneralInscripcionesLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 174, Short.MAX_VALUE))
            .addGroup(PanelGeneralInscripcionesLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(panelFichaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelGeneralInscripcionesLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(labelTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        PanelGeneralInscripcionesLayout.setVerticalGroup(
            PanelGeneralInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralInscripcionesLayout.createSequentialGroup()
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelGeneralInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo3)
                    .addComponent(labelTitulo4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFichaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGeneralInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGeneralInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void generarRecibo(Model.Inscripcion datos) {
       panelFichaPago.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
    panelFichaPago.removeAll();
    panelFichaPago.setBackground(new java.awt.Color(204, 255, 255));

    for (Model.Curso c : datos.getListaCursosInscritos()) {
        javax.swing.JLabel lbl = new javax.swing.JLabel("  " + c.getNombre() + " ................. $" + c.getCosto());
        lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // Fuente más grande
        panelFichaPago.add(lbl);
    }
    
    labelTotalFinalPagar.setText("$" + String.format("%.2f", datos.getMontoTotal()));
    labelFechaEmision.setText("Fecha de emision: " + datos.getFechaEmision());
    labelIdTransaccion.setText("ID de transaccion: " + datos.getIdTransaccion());
    
    panelFichaPago.revalidate();
    panelFichaPago.repaint();
    }

    public void setAccionReinicio(java.awt.event.ActionListener accion) {
        // Quitamos cualquier listener previo para evitar que se cierre la app
    for(java.awt.event.ActionListener al : btnNuevaInscripcion.getActionListeners()) {
        btnNuevaInscripcion.removeActionListener(al);
    }
    btnNuevaInscripcion.addActionListener(accion);
    }


    private void btnNuevaInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaInscripcionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnNuevaInscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGeneralInscripciones;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JButton btnNuevaInscripcion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFechaEmision;
    private javax.swing.JLabel labelIdTransaccion;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelTitulo3;
    private javax.swing.JLabel labelTitulo4;
    private javax.swing.JLabel labelTitulo5;
    private javax.swing.JLabel labelTotalFinalPagar;
    private javax.swing.JPanel panelFichaPago;
    // End of variables declaration//GEN-END:variables
}
