package Vista;

/**
 *
 * @author Fernando garces
 */
public class PantallaInscripcion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaInscripcion.class.getName());

    private Control.InscripcionController controller;
    private int seleccionadosCount = 0;

    /**
     * Creates new form PantallaInscripcion
     */
    public PantallaInscripcion() {
        initComponents();
        this.setSize(1024, 720); // Tamaño estático basado en tu captura
    this.setResizable(false);
    this.setLocationRelativeTo(null);

    // Ajustamos el fondo general
    PanelGeneralInscripciones.setBackground(java.awt.Color.WHITE);
    
    // Configuramos los paneles azules para que tengan su color y tamaño fijo
    panelCursos.setBackground(new java.awt.Color(204, 255, 255));
    panelFichaPago.setBackground(new java.awt.Color(204, 255, 255));
    
    // Agregamos un margen para que no toquen los bordes de la ventana
    panelCursos.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    panelFichaPago.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

    // Forzamos el Layout de los paneles para que los elementos fluyan hacia abajo
    panelCursos.setLayout(new java.awt.GridLayout(0, 1, 0, 10)); 
    panelFichaPago.setLayout(new java.awt.GridLayout(0, 1, 0, 5));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneralInscripciones = new javax.swing.JPanel();
        PanelTitulo = new javax.swing.JPanel();
        labelTitulo1 = new javax.swing.JLabel();
        labelNumCursos = new javax.swing.JLabel();
        panelCursos = new javax.swing.JPanel();
        panelFichaPago = new javax.swing.JPanel();
        labelTitulo3 = new javax.swing.JLabel();
        labelCursosSeleccionados = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelTotalPagar = new javax.swing.JLabel();
        labelTitulo5 = new javax.swing.JLabel();
        btnFinalizarFicha = new javax.swing.JButton();
        labelTitulo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelGeneralInscripciones.setBackground(new java.awt.Color(255, 255, 255));

        PanelTitulo.setBackground(new java.awt.Color(102, 0, 204));

        labelTitulo1.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        labelTitulo1.setText("Portal de inscripciones - ITSON");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(labelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelTitulo1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        labelNumCursos.setBackground(new java.awt.Color(153, 153, 153));
        labelNumCursos.setForeground(new java.awt.Color(0, 0, 102));
        labelNumCursos.setText("8 Cursos");

        panelCursos.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout panelCursosLayout = new javax.swing.GroupLayout(panelCursos);
        panelCursos.setLayout(panelCursosLayout);
        panelCursosLayout.setHorizontalGroup(
            panelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );
        panelCursosLayout.setVerticalGroup(
            panelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelFichaPago.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout panelFichaPagoLayout = new javax.swing.GroupLayout(panelFichaPago);
        panelFichaPago.setLayout(panelFichaPagoLayout);
        panelFichaPagoLayout.setHorizontalGroup(
            panelFichaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        panelFichaPagoLayout.setVerticalGroup(
            panelFichaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        labelTitulo3.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        labelTitulo3.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo3.setText("Cursos disponibles");

        labelCursosSeleccionados.setBackground(new java.awt.Color(153, 153, 153));
        labelCursosSeleccionados.setForeground(new java.awt.Color(0, 0, 102));
        labelCursosSeleccionados.setText("0 Seleccionados");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelTotalPagar.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        labelTotalPagar.setForeground(new java.awt.Color(0, 0, 0));
        labelTotalPagar.setText("$0.00");

        labelTitulo5.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        labelTitulo5.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo5.setText("Subtotal a pagar:");

        btnFinalizarFicha.setBackground(new java.awt.Color(102, 51, 255));
        btnFinalizarFicha.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        btnFinalizarFicha.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizarFicha.setText("Finalizar e imprimir ficha");
        btnFinalizarFicha.addActionListener(this::btnFinalizarFichaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(labelTitulo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTotalPagar)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 83, Short.MAX_VALUE)
                .addComponent(btnFinalizarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalPagar)
                    .addComponent(labelTitulo5))
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        labelTitulo4.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        labelTitulo4.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo4.setText("Mis cursos inscritos");

        javax.swing.GroupLayout PanelGeneralInscripcionesLayout = new javax.swing.GroupLayout(PanelGeneralInscripciones);
        PanelGeneralInscripciones.setLayout(PanelGeneralInscripcionesLayout);
        PanelGeneralInscripcionesLayout.setHorizontalGroup(
            PanelGeneralInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelGeneralInscripcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGeneralInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGeneralInscripcionesLayout.createSequentialGroup()
                        .addComponent(labelTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(labelNumCursos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCursosSeleccionados)
                        .addGap(18, 18, 18))
                    .addGroup(PanelGeneralInscripcionesLayout.createSequentialGroup()
                        .addComponent(panelCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFichaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(PanelGeneralInscripcionesLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelGeneralInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGeneralInscripcionesLayout.createSequentialGroup()
                    .addContainerGap(347, Short.MAX_VALUE)
                    .addComponent(labelTitulo4)
                    .addGap(200, 200, 200)))
        );
        PanelGeneralInscripcionesLayout.setVerticalGroup(
            PanelGeneralInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralInscripcionesLayout.createSequentialGroup()
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelGeneralInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo3)
                    .addComponent(labelNumCursos)
                    .addComponent(labelCursosSeleccionados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelGeneralInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelFichaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelGeneralInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelGeneralInscripcionesLayout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(labelTitulo4)
                    .addContainerGap(417, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGeneralInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGeneralInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void inicializarConControlador(Control.InscripcionController controller) {
        this.controller = controller;
        cargarCatalogo();
    }
    
    public void actualizarInterfaz(int seleccionados, int restantes, double total) {
    labelCursosSeleccionados.setText(seleccionados + " Seleccionados");
    labelNumCursos.setText(restantes + " Cursos"); // Ahora sí baja el número
    labelTotalPagar.setText("$" + String.format("%.2f", total));
}

    private void cargarCatalogo() {
       // Cada curso ocupará una fila completa dentro de su mitad
    panelCursos.setLayout(new java.awt.GridLayout(8, 1, 5, 5)); 
    panelFichaPago.setLayout(new java.awt.GridLayout(10, 1, 5, 5)); // Espacio para 8 cursos + margen
    
    Model.Curso[] cursos = {
        new Model.Curso("Arquitectura de software", 450.00),
        new Model.Curso("Aplicaciones web", 500.00),
        new Model.Curso("Pruebas de software", 450.00),
        new Model.Curso("Innovacion tecnologica", 400.00),
        new Model.Curso("Axiologia para la profesion", 400.00),
        new Model.Curso("Sistemas empotrados", 450.00),
        new Model.Curso("Sistemas distribuidos", 550.00),
        new Model.Curso("Analisis de algoritmos", 500.00)
    };

    for (Model.Curso c : cursos) {
        javax.swing.JButton btn = new javax.swing.JButton(c.getNombre() + " $" + c.getCosto() + " [Inscribir]");
        btn.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btn.addActionListener(e -> {
            controller.seleccionarCurso(c);
            javax.swing.JLabel lbl = new javax.swing.JLabel("  • " + c.getNombre() + "  $" + c.getCosto());
            lbl.setFont(new java.awt.Font("Segoe UI", 1, 13));
            panelFichaPago.add(lbl);
            btn.setEnabled(false); // En lugar de desaparecer, se deshabilita para mantener el layout
            panelFichaPago.revalidate();
            panelFichaPago.repaint();
        });
        panelCursos.add(btn);
    }
    }

    public void limpiarParaNuevaInscripcion() {
        seleccionadosCount = 0;
        labelCursosSeleccionados.setText("0 Seleccionados");
        labelTotalPagar.setText("$0.00");
        panelFichaPago.removeAll();
        panelCursos.removeAll();
        cargarCatalogo();
        panelCursos.revalidate();
    }

    public void actualizarTotal(double t) {
        labelTotalPagar.setText("$" + String.format("%.2f", t));
    }

    private void btnFinalizarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarFichaActionPerformed
        controller.finalizarProceso(); // Llama al metodo del controlador
    }//GEN-LAST:event_btnFinalizarFichaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // 1. Instanciar esta misma pantalla
            PantallaInscripcion vista = new PantallaInscripcion();

            // 2. Crear el controlador pasandole la vista
            Control.InscripcionController control = new Control.InscripcionController(vista);

            // 3. Conectar el controlador a la vista para que cargue los cursos
            vista.inicializarConControlador(control);

            // 4. Hacerla visible
            vista.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGeneralInscripciones;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JButton btnFinalizarFicha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCursosSeleccionados;
    private javax.swing.JLabel labelNumCursos;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelTitulo3;
    private javax.swing.JLabel labelTitulo4;
    private javax.swing.JLabel labelTitulo5;
    private javax.swing.JLabel labelTotalPagar;
    private javax.swing.JPanel panelCursos;
    private javax.swing.JPanel panelFichaPago;
    // End of variables declaration//GEN-END:variables
}
